export default {
	weptileBlog: 'Weptile Blog',
	weptileCompanyContentTitle: 'We are more than just a company',
	weptileCompanyContentText:
		'Lorem ipsum dolor sit amet, consectetur adipisicing elit,sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
	weptileText: 'We are The Weptile Team',
	checkUsrPsw: 'Please check your username and password',
	loginToAccText: 'Login to your account',
	login: 'Login',
	loginAccountAsking: 'Don\'t have an account?',
	loginCreateAccButtonText: 'Create Now',
	forgotPass: 'Forgot password?',
	changePassInfo: 'You can change your password here.',
	forgotPassInfo:
		'Enter your user account\'s email address and we will send you a password reset code.',
	passResetEmail: 'Send password reset email',
	changePass: 'Change Password',
	signUpNow: 'Sign up now',
	signUp: 'Sign Up',
	notFound: '404 Not Found',
	sendMessage: 'Send Message',
	allText: 'All',
	postedOn: 'Posted on ',
	team: 'PROFESSIONAL TEAM',
	weAre: 'We are WooCommerce Expert Software & App Agency',
	aboutUs: 'About Us',
	aboutUsContentTitle:
		'Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics',
	aboutUsContentText:
		'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim',
	aboutFormText: 'Send us a message',
	requiredError: 'Please don\'t pass empty any required field',
	specificRequiredError: 'You can\'t pass empty this field.',
	addNewCategory: 'Add A New Category',
	addNewDepartment: 'Add A New Department',
	departmentName: 'Department Name',
	teamList: 'Team List',
	addTeamMember: 'Add A New Team Member',
	continueReading: 'Continue reading',
	search: 'Search',
	loading: 'Loading...',
	featureList: 'Feature List',
	addNewFeature: 'Add A New Feature',
	addNewPost: 'Add A New Post',
	view: 'View',
	sameCategoryMessage: 'Sorry! Same category name exist before.',
	sameDepartmentMessage: 'Sorry! Same category name exist before.',
	close: 'Close',
	add: 'Add',
	clear: 'Clear',
	save: 'Save',
	edit: 'Edit',
	delete: 'Delete',
	update: 'Update',
	editAboutUs: 'Edit About Us',
	uploadPhoto: 'Upload a photo',
	requestInProgress: 'Your request is in progress',
	chooseCategory: 'Choose a category',
	name: 'Name',
	requiredName: 'Name *',
	department: 'Department',
	title: 'Title',
	requiredTitle: 'Title*',
	text: 'Text',
	requiredText: 'Text*',
	icon: 'Icon',
	selectIcon: 'Select an icon',
	featureTitle: 'Feature Title',
	featureText: 'Feature Text',
	requiredFullName: 'Full name *',
	fullName: 'Full name',
	firstName: 'First name',
	requiredFirstName: 'First name *',
	lastName: 'Last name',
	requiredUsername: 'Username *',
	username: 'Username',
	requiredLastName: 'Last name *',
	phone: 'Phone',
	category: 'Category',
	categories: 'Categories',
	email: 'Email address',
	requiredEmail: 'Email address *',
	password: 'Password',
	requiredPassword: 'Password *',
	categoryName: 'Category Name',
	company: 'Company',
	companyName: 'CompanyName',
	requiredMessage: 'Message *',
	yourMessage: 'Write your message',
	joinDiscussion: 'Join the discussion and leave a comment!',
	categoryList: 'Category List',
	departmentList: 'Department List',
	copyright: '© Copyright',
	allRightReserved: '. All Rights Reserved, Weptile.',
	socialMedia: 'Social Media',
	loginCheckErrorForComment: 'You need to login to comment',
	userPagesText: 'User pages',
	adminPagesText: 'Admin pages',
	userCreatedSuccessfully: 'User has been created successfully',
	checkYourEmail: 'Please check your email for confirmation code',
	confirmationCode: 'Confirmation Code',
	newPass: 'New Password',
	confirmPass: 'Confirm Password',
	passChangedSuccessfully: 'Password has been changed successfully',
	passwordsNotMatch: 'Passwords are not matching. Please be sure writing the same passwords.',
	loginSuccessful: 'Login is successful',
	systemError: 'A problem has occurred in the system. Please try again later.',
	invalidEmailError: 'You have entered an invalid email address!',
	invalidPasswordError:
		'Password should be between 8 to 15 characters which contain at least one lowercase letter, one uppercase letter, one numeric digit, and one special character.',
	profile: 'Profile',
	interestedCategories: 'Interested Categories',
	uploadAvatar: 'Upload an wb-avatar',
	userDataChangedSuccessfully: 'User information has been successfully updated.',
	hi: 'Hi',
	userPageTitle: 'User',
	settings: 'settings',
};
